### ISSUE TITLE
Information about Evaluation

### ISSUE THREAD

**Issue by asif-hanif** [microsoft/Pengi#14]
Hi,
Thanks for the great work.
I have a question regarding the evaluation on US8K dataset. This dataset has 10 folds and its [website](https://urbansounddataset.weebly.com/urbansound8k.html) recommends using 10-fold cross validation to obtain average test results. Could you please confirm if you used 10-fold cross validation. I have evaluated **pengi** model on **each fold separately** and average accuracy across these folds do not match with the number reported in paper (i.e. Accuracy=0.7185 on US8K from Table 3). I get average accuracy around 0.55.

**Comment by soham97** [comment]
Hi @asif-hanif, make sure you are resampling the dataset to 44.1 kHz. The model performance drops when a different sampling rate is used.

**Comment by asif-hanif** [comment]
Thanks for the feedback. 
I have not changed the default settings related to audio pre-processing.
Could you kindly provide a sudo-code like high-level steps to perform audio classification.

I have used cosine-similarity (between audio embedding and text embeddings) based method to perform audio classification. For text embeddings, I have a template for each class like this "This audio has sound of {CLASS}". Class with highest cosine similarity with audio embedding is assigned as the predicted label.

Could you confirm if you used similar procedure for closed-ended audio classification problem. 
Thanks!
