### ISSUE TITLE
About the ASR task.

### ISSUE THREAD

**Issue by wangwen-banban** [microsoft/Pengi#17]
Hi! Thanks for the great work! I have a question regarding the ASR capability of Pengi. I noticed that there are some speech training datasets, but they seem to focus primarily on classification tasks. In your research, did you explore Pengi’s performance on ASR tasks? If so, how did it perform? I would greatly appreciate any insights you could share. Thank you!

**Comment by soham97** [comment]
Hi @wangwen-banban, Pengi does not support the ASR task. It can only do paralinguistics tasks related to speech. In theory, the next-token prediction objective loss could also work for ASR, assuming the audio encoder is similar to Wav2vec2 or WavLM. I suggest looking into papers on SpeechLM, which have likely explored this topic. Hope this helps!

**Comment by wangwen-banban** [comment]
Thanks a lot.
