### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by zhifengkong** [microsoft/Pengi#5]
Hi, 

I'd like to ask if you will release the evaluation code on standard benchmarks (such as clotho and audiocaps)? And what temperature / num_beams did you use to obtain the results? Thanks!

**Comment by soham97** [comment]
Hi @FengNiMa, the repo hosts only evaluation code, and the subsequent release of evaluation dataloaders is not planned. The downstream task evaluation uses a beam size of 5 and a temperature of 1.0. This is kept the same for all downstream tasks.

Hope this helps and feel free to email me with any questions.

**Comment by zhifengkong** [comment]
Thanks!
