### ISSUE TITLE
Sample rate has been changed

### ISSUE THREAD

**Issue by Yonnie1331** [microsoft/Pengi#6]
Hello,
for the lines 171-184, in wrapper.py, func load_audio_into_tensor,
should 'sample_rate' perhaps be 'resample_rate'?
Since in line 164, the audio has already been resampled

**Comment by soham97** [comment]
Good spot @Yonnie1331, its fixed in the latest commit [[1]](https://github.com/microsoft/Pengi/commit/636394c36be6e2bb5053601c910409a30057029c)
